### PR TITLE
Updated  visualizers and mainpage using KIVY GUI 

### PR DESCRIPTION
**Pull request by Priyaanshucodez**
ma'am you can check the file now #133  ....if in case of any discrepancies ..plz tell me ..I will resolve it

### CODE REVIEW

**Review by dinxsh — CHANGES_REQUESTED** [review]
could you add an screenshot of the final output since there are a decent lot changes

**Comment by Priyaanshucodez** [comment]
yes sure ... I have actually modified the 4 main visualizers using KivyGUI  as an Alternative to PySimpleGUI giving the same output as the previous code.


Screenshot (54)
Screenshot (53)
Screenshot (52)
Screenshot (50)

**Comment by Priyaanshucodez** [comment]
used it as an alternative since PySimpleGUI was not working from the user end referred to issue #133

**Review by dinxsh — CHANGES_REQUESTED** [review]
a lot can be improved in terms of the UI starting from the buttons, colors and window of course also fixing text overflowing buttons, improving UI and making it near for mic to sound intensity. looks good to merge otherwise.

**Comment by Priyaanshucodez** [comment]
@dinxsh I know Sir but since I had to follow the code of conduct of gssoc ...So I worked according to the issue and just updated the code with new GUI instead of improving it further ...Actually Gssoc is my first open source program so I was really cautious :) .

**Comment by dinxsh** [comment]
> @dinxsh I know Sir but since I had to follow the code of conduct of gssoc ...So I worked according to the issue and just updated the code with new GUI framework instead of improving it further ...Actually Gssoc is my first open source program so I was really cautious :) .

its a good contribution for sure just make these small fixes like text overflowing buttons, and making mic to sound intensity clear and neat (over the buttons section) we'll be sure to merge it for you @Priyaanshucodez 

you can dm on discord for further help at dinxsh

**Comment by Priyaanshucodez** [comment]
thank you so much @dinxsh sir but I had a request  can i please take these small fixes as a new level 1 issue ...Actually this is my first decent contribution as i couldn't contribute to gssoc before due to college examinations so if you feel its decent enough to merge can you do it from your side ?

**Review by Soumya-Kushwaha — APPROVED** [review]

**Review by dinxsh — APPROVED** [review]
looks good to me, looking forward to more updates for this

**Comment by Priyaanshucodez** [comment]
> looks good to me, looking forward to more updates for this

Sure Sir 👍

**Comment by dinxsh** [comment]
do create issues to fix these asap to avoid new confusion for new contributors and ping me in those @Priyaanshucodez

**Pull request merged**
