### PR TITLE
Energy envelope-over-time

### PR DESCRIPTION
**Pull request by PDBharadwaj**
Added a new visualizer for 'energy envelope-over-time'. It shows how the energy of a system changes and is distributed over a period of time. It also provides a smoothed representation of the amplitude variations of the audio signal over time. This can be useful for understanding how the signal’s loudness or energy changes throughout its duration.
It fixes the issue #181
@dinxsh @Soumya-Kushwaha Please review and merge the PR.

### CODE REVIEW

**Review by dinxsh — CHANGES_REQUESTED** [review]
add a screenshot of the output and also add this file to the main file

**Comment by PDBharadwaj** [comment]
> add a screenshot of the output and also add this file to the main file

WhatsApp Image 2024-08-03 at 11 15 37 AM

https://github.com/user-attachments/assets/e5af8cc6-92ca-46ee-a93d-0ed116e02a16

Added screenshot and video of the output. Also added this file to the main file. 
@dinxsh @Soumya-Kushwaha Please review and merge my PR.

**Review by dinxsh — APPROVED** [review]
good job!

**Review by Soumya-Kushwaha — APPROVED** [review]

**Comment by PDBharadwaj** [comment]
@dinxsh @Soumya-Kushwaha Points are not added to this PR.

**Pull request merged**
