### PR TITLE
Added Spectral Gating

### LINKED ISSUE #109: [Feature]: Added Spectral Gating method of noise reduction
**Is your feature request related to a problem? Please describe.**
While working on the previous noise reduction task using PCEN, it showed a significant reduction in noise samples unwanted to the individual segment. But I have come across a new method which might help to visualize the effect more and help in higher reduction levels.

**Describe the solution you'd like**
I can use spectral gating to get a better visualization on the work and get better results.

**Describe alternatives you've considered**
Couldn't come across anymore alternatives at this point.

I would like to take this task under GSSOC'24.

Hope I might it to your sight..

Thank You

### PR DESCRIPTION
**Pull request by Soubeer**
PR Title
Added model for noise reduction-Spectral Gating

Description
A method of reducing noise from incoming sound has been added
Used filtering for low frequencies to capture enough detail and not lose important analytical data.
There is no particular dataset, any sound sample can be used.

Linked Issue
Closes #109 [Added Spectral Gating method of noise reduction]

Changes and Additions:
A method of reducing noise from incoming sound has been added
Used filtering for low frequencies to capture enough detail and not lose important analytical data
There is no particular dataset, any sound sample can be used

Testing and Validation
Tested on sound samples to find low frequency zones and correspond the same with sample labels
Successfully reduced sound decibels from incoming noise by checking the sound wave graph

Additional Context or Information
The fork is updated and it only additionally includes the file for the model to work

Checklist
Please ensure you've completed the following tasks:

✓ Code is up to date with the project's latest version
✓ All tests have been run and passed
✓ Code has been reviewed for correctness and readability
✓ Followed the project's coding guidelines

### CODE REVIEW

**Comment by Soubeer** [comment]
@Soumya-Kushwaha can you check my PR? its done

**Comment by Soubeer** [comment]
@Soumya-Kushwaha my task is complete , can you check and merge the PR if its okay and provide me with the labels?

**Comment by Soumya-Kushwaha** [comment]
@dinxsh plz go through once.

**Review by dinxsh — APPROVED** [review]
LGTM

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
