### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by Khushalsarode**
1. new named main landing to "Home.py"
2. removed calls from menu in each wave page code
3. Calling each wave code from home window only
4. added an image on home for looking visual appealing
5. adjust exit & menu buttons on home window
6. adjust padding and window sized where needed.

### CODE REVIEW

**Comment by Khushalsarode** [comment]
Hey @Soumya-Kushwaha need review!
Gssoc24

**Comment by dinxsh** [comment]
could you add a screenshot/video and follow the pr template @Khushalsarode

**Comment by Khushalsarode** [comment]
issue #108

**Comment by dinxsh** [comment]
would still require you to resolve conflicts before moving forward @Khushalsarode

**Review by dinxsh — CHANGES_REQUESTED** [review]
would still require you to resolve conflicts before moving forward @Khushalsarode

**Pull request closed without merging**
