### PR TITLE
Documentation Update : (Improvise Documentation #7)

### PR DESCRIPTION
**Pull request by saiyam-sandhir**
This pull request is response to the assignment of issue #7 to me by maintainer @Soumya-Kushwaha 
I hope you liked the changes i made to documentation, please suggest any improvements if needed

### CODE REVIEW

**Comment by saiyam-sandhir** [comment]
You can get a preview of the update README.md file here https://github.com/saiyam-sandhir/SoundScape/tree/documentation

**Comment by Soumya-Kushwaha** [comment]
@saiyam-sandhir Do you think we'll be able to keep all the processors on README when we have a slightly higher number of those?
image

Please come up with some other idea for this.

Also, I'd request you to create a new branch in the (updated) fork, perform all changes in the same, and then generating a final PR.
This will count all your changes as 1 major change, instead of multiple smaller changes.

We'll be assigned project mentors soon. I believe they'll be able to help you more regarding such thins :)

**Comment by skymallow** [comment]
How will we know who our assigned project mentor is?

**Comment by Soumya-Kushwaha** [comment]
@skymallow I'll let you know.

**Comment by saiyam-sandhir** [comment]
> @saiyam-sandhir Do you think we'll be able to keep all the processors on README when we have a slightly higher number of those? image
> 
> Please come up with some other idea for this.
> 
> Also, I'd request you to create a new branch in the (updated) fork, perform all changes in the same, and then generating a final PR. This will count all your changes as 1 major change, instead of multiple smaller changes.
> 
> We'll be assigned project mentors soon. I believe they'll be able to help you more regarding such thins :)

ok i will think of new ideas after communicating with the mentor

**Pull request closed without merging**
