### PR TITLE
Created the new Python Decibles file

### PR DESCRIPTION
**Pull request by Harish-2003**
## PR Title
All Requirements Satisfied: Real-time Audio Spectrogram Plotting

## Description
This PR implements real-time audio spectrogram plotting using PySimpleGUI, PyAudio, NumPy, SciPy, and Matplotlib. It enables users to visualize audio signals in the form of a spectrogram, providing insights into the frequency content over time.

## Linked Issue
Please link the issue that this PR resolves in the format: `#44 Real time Decibal tracking Feature`

## Changes and Additions
- Implemented real-time audio spectrogram plotting functionality
- Integrated PySimpleGUI for the user interface
- Utilized PyAudio for audio input streaming
- Processed audio data using NumPy and SciPy
- Visualized spectrogram using Matplotlib
- Designed y-axis tick labels based on decibel levels

## Testing and Validation
The changes were tested and validated using the following steps:
1. Simulated real-time audio input using predefined audio data.
2. Observed the spectrogram plot in the GUI window.
3. Verified that the y-axis tick labels corresponded to the expected decibel levels.
4. Ensured smooth operation and responsiveness of the GUI.

## Additional Context or Information
The implementation follows the design principles outlined in the project's architecture and adheres to coding standards. The code is well-commented and organized for readability and maintainability.

## Checklist
Please ensure you've completed the following tasks:
- [x] Code is up to date with the project's latest version
- [x] All tests have been run and passed
- [x] Code has been reviewed for correctness and readability
- [x] Followed the project's coding guidelines

## References
- [Contribution.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Contribution.md)
- [Installation.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Installation.md)
- [References.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/References.md)

### CODE REVIEW

**Comment by Harish-2003** [comment]
@Soumya-Kushwaha please let me know if there are any changes that need to be done

**Comment by Soumya-Kushwaha** [comment]
PR description should be as per the PR template.

**Comment by Harish-2003** [comment]
oh okay will change

**Comment by Harish-2003** [comment]
Updated the thing please check and let me know if there are any changes that are needed to be done  @Soumya-Kushwaha

**Pull request closed without merging**
