### PR TITLE
Improved the UI and updated two py files

### PR DESCRIPTION
**Pull request by Priyaanshucodez**
Improved The UI with reference to #157 and updated two more files (Amplitude visualizer and Energy visualizer)

### CODE REVIEW

**Comment by Priyaanshucodez** [comment]
@dinxsh created the pr for the issue #157

**Review by dinxsh — CHANGES_REQUESTED** [review]
looks good, could you add more margins between the buttons and charts in  amplifier-frequency.py and energy-frequency .py file @Priyaanshucodez

**Comment by Priyaanshucodez** [comment]
> looks good, could you add more margins between the buttons and charts in amplifier-frequency.py and energy-frequency .py file @Priyaanshucodez

ok sir

**Comment by Priyaanshucodez** [comment]
@dinxsh i tried to increase the Margin but somehow it wasn't looking good so i changed the UI to a simpler version opening three different tabs for each task .
just have a look ...should i merge this ?
Screenshot (60)
Screenshot (61)
Screenshot (62)

**Comment by Priyaanshucodez** [comment]
> @dinxsh i tried to increase the Margin but somehow it wasn't looking good so i changed the UI to a simpler version opening three different tabs for each task . just have a look ...should i merge this ? Screenshot (60) Screenshot (61) Screenshot (62)

this is just for energy -frequency.py ...I did the same for Amplitude-frequency.py

**Comment by Priyaanshucodez** [comment]
i created the pr @dinxsh sir and @Soumya-Kushwaha Ma'am ....Just have a look and I had a request that if you could assign this as a level 3 issue instead of level 2 since a lot of changes i had to do ..I would be really grateful ...Rest it was great collaborating on this project with both of you .

**Review by dinxsh — APPROVED** [review]
assigned labels, looks neat. good job!

**Comment by Priyaanshucodez** [comment]
@Soumya-Kushwaha Ma'am your review is left ...Kindly review and close the issue .

**Comment by Priyaanshucodez** [comment]
> @Soumya-Kushwaha Ma'am your review is left ...Kindly review and close the issue .

Plz review it from your side

**Comment by Priyaanshucodez** [comment]
@dinxsh Sir there has been no reply from @Soumya-Kushwaha Ma'am ...I emailed her too ..Kindly inform her from your side .

**Comment by Priyaanshucodez** [comment]
@Soumya-Kushwaha Ma'am plz review the PR ..It's been over 1 week now

**Comment by Priyaanshucodez** [comment]
Ma'am plz close this one ...@Dinesh changed the level from 2 to 3

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
