### PR TITLE
Add Title to Frequency Spectrum Plot and Improve Error Handling

### PR DESCRIPTION
**Pull request by Swapnilden**
### Closes: #119 

The absence of a title in the frequency spectrum plot made it less informative and clear. Additionally, the lack of error handling in critical sections of the code could cause the program to crash unexpectedly, leading to a poor user experience.

In this pull request I have added:

1. Title Addition:

Added a line of code to set the title of the frequency spectrum plot to "Frequency Spectrum".

2. Error Handling:

Incorporated try-except blocks around the audio callback function and the plot updating section to catch and report errors without crashing the program.

These changes aim to improve the usability and robustness of the application.

### CODE REVIEW

**Comment by dinxsh** [comment]
could you resolve the conflicts @Swapnilden

**Review by dinxsh — CHANGES_REQUESTED** [review]
could you resolve conflicts @Swapnilden

**Comment by Swapnilden** [comment]
@dinxsh ya sure

**Review by dinxsh — APPROVED** [review]
LGTM, ready for merge. good work!

**Comment by Swapnilden** [comment]
@dinxsh Thanks for your kind words

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
