### PR TITLE
Resolved #86

### LINKED ISSUE #86: Readme Update_[feature]
Currently Our readme.md file is not looking good 

It is looking like a learn.md file I would suggest to @Soumya-Kushwaha @Passionatelytoooadorable assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .

### PR DESCRIPTION
**Pull request by Meetjain1**
Updated README file to a fully new version as I stated , 

closes #86

### CODE REVIEW

**Review by dinxsh — CHANGES_REQUESTED** [review]
not needed at the moment, sorry! removed some important sections like contact also unnecessary changes like one word changes! try to add unique things to the readmes like badges or status, check popular open source projects for inspiration and then we'll consider :)

**Comment by Meetjain1** [comment]
> not needed at the moment, sorry! removed some important sections like contact also unnecessary changes like one word changes! try to add unique things to the readmes like badges or status, check popular open source projects for inspiration and then we'll consider :)

Don't you think these things you have to tell me when I get assigned for this task ? What do you mean by not needed ? 

After giving a lot of time to this task I get to know these are one word changes , (Added 72 lines for your kind information) btw and the one word changes is of alignment and i dont think these type of language seems good in open source (one word changes) only, and the contact section you are talking about is placed in a section where it needs to be . And in some of the popular open source projects of gssoc, readme is build by me .
And can you elaborate more on badges or status that you are talking about ? @dinxsh

**Comment by Meetjain1** [comment]
.

**Comment by dinxsh** [comment]
> > not needed at the moment, sorry! removed some important sections like contact also unnecessary changes like one word changes! try to add unique things to the readmes like badges or status, check popular open source projects for inspiration and then we'll consider :)
> 
> Don't you think these things you have to tell me when I get assigned for this task ? What do you mean by not needed ?
> 
> After giving a lot of time to this task I get to know these are one word changes , (Added 72 lines for your kind information) btw and the one word changes is of alignment and i dont think these type of language seems good in open source (one word changes) only, and the contact section you are talking about is placed in a section where it needs to be . And in some of the popular open source projects of gssoc, readme is build by me . And can you elaborate more on badges or status that you are talking about ? @dinxsh

firstly i wasnt the one assigning you that issue wouldve closed or diverted you to a better idea, secondly did say sorry don't get too cocky, just said come up with something new and we'll love to accept it as for badges look at any popular open source program and you'll get the idea, this isn't the first change readme issue we've received. just trying to guide you to the right path!

**Pull request closed without merging**
