### PR TITLE
Added zero-crossing-line visualizer

### LINKED ISSUE #162: [feature]Add a new visualizer for zero-crossing rate
**Describe the feature you'd like to add**
I wanted to add a new visualizer to the project. This keeps track of where the sound parameters cross the zero line and show it on the plot.
@Soumya-Kushwaha  I would like to work on this issue. Please assign me this issue under GSSoC'24.

### PR DESCRIPTION
**Pull request by PDBharadwaj**
I have added zero-crossing line visualizer to the repo. 
This PR fixes #162.
@Soumya-Kushwaha @dinxsh Kindly review and merge this PR.

### CODE REVIEW

**Review by dinxsh — CHANGES_REQUESTED** [review]
lgtm , could you add a screenshot of the output

**Comment by PDBharadwaj** [comment]
> lgtm , could you add a screenshot of the output


https://github.com/user-attachments/assets/7b4a39d1-8fb8-4412-a7e4-df8b9ca72987

**Comment by PDBharadwaj** [comment]
@dinxsh @Soumya-Kushwaha  Please review and merge my PR.

**Review by dinxsh — APPROVED** [review]
lgtm, good job!

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
