### PR TITLE
New UI to call and python pages from home page #108

### LINKED ISSUE #108: Create an new User Interface for app and linking the functions window to it!
**Is your feature request related to a problem? Please describe.**
Current application when clicked on menu button on mainlanding.py doesn't open an respective wave form code also the drop down in each function code dont work when called.

**Describe the solution you'd like**
so creating an loop application from main page only such that all the function can be called from there and when closed will loop back to main. Also trying to make some changes into main page to adjust buttons. Will thus remove an call from list menu from each functionality page.

**Additional context**
### Before:
Screenshot 2024-06-01 171311

### After & Working:
Screenshot 2024-06-01 185241

@Soumya-Kushwaha
`Can I get this issue assigned! for worked upon?`

Gssoc24

### PR DESCRIPTION
**Pull request by Khushalsarode**
## PR Title
Calling python pages from home page

## Description
- renamed main landing to home 
- added new layout design to home 
- calling function/waveforms from home page
- added graphics image on home page

## Linked Issue
 Closes #108 

## Changes and Additions
- change of code in home
- adding of image in folder
- adding gitignore

## Testing and Validation
- call working fine
- pages loading 

## Additional Context or Information
- wanted to remove menu call for each page from each page but due to conflict can't & they are not functional

## Checklist
Please ensure you've completed the following tasks:
- [ x ] Code is up to date with the project's latest version
- [ x ] All tests have been run and passed
- [ x ] Code has been reviewed for correctness and readability
- [ x ] Followed the project's coding guidelines

### CODE REVIEW

**Comment by Khushalsarode** [comment]
need review?

**Review by dinxsh — CHANGES_REQUESTED** [review]
would suggest resolving conflicts before moving ahead

**Review by dinxsh — CHANGES_REQUESTED** [review]
did u test this? also just to be sure could you send me the screenshots of the output with your changes

**Comment by Khushalsarode** [comment]
> did u test this? also just to be sure could you send me the screenshots of the output with your changes

Yes tested running fine
Sure

**Review by dinxsh — APPROVED** [review]
looks great to me, good job!

**Review by jessicachawla — APPROVED** [review]
looks good to me

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
