### PR TITLE
 Add a new Lissajous Curves Visualizer

### PR DESCRIPTION
**Pull request by abckhush**
Fixes: #166 

image
image
image

The curves are generated in random motion.

@dinxsh @Soumya-Kushwaha Kindly review the PR.

### CODE REVIEW

**Review by dinxsh — APPROVED** [review]
looks good, nice work!

**Comment by abckhush** [comment]
@Soumya-Kushwaha @jessicachawla Kindly review.

**Comment by abckhush** [comment]
@Soumya-Kushwaha @jessicachawla Kindly review. Only a few days are left.

**Review by jessicachawla — APPROVED** [review]

**Comment by abckhush** [comment]
Thank you! Could you merge this as well along with the level?

**Pull request merged**
