### PR TITLE
adding barplot visualizer

### LINKED ISSUE #180: adding Bar-histo visualizer
barplot

@dinxsh @Soumya-Kushwaha

### PR DESCRIPTION
**Pull request by Khushalsarode**
closes #180

### CODE REVIEW

**Comment by Khushalsarode** [comment]
@dinxsh @Soumya-Kushwaha

**Review by dinxsh — CHANGES_REQUESTED** [review]
add a screenshot and add your files name to main,py

**Comment by Khushalsarode** [comment]
sure

**Comment by Khushalsarode** [comment]
> add a screenshot and add your files name to main,py

**Review by dinxsh — APPROVED** [review]
good job!

**Review by jessicachawla — APPROVED** [review]
Well done

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
