### PR TITLE
Update Amplitude-Frequency-Visualizer.py

### PR DESCRIPTION
**Pull request by RavindranathTagor**
## PR Title
Enhancements to Amplitude-Frequency-Visualizer Functionality

## Description
This PR introduces several new features to the Amplitude-Frequency-Visualizer.py script, including the ability to pause and resume the audio stream, save the audio data and frequency plot, and select a directory for saving files. The frequency plot has been enhanced with gridlines and a legend, and the GUI layout has been updated to accommodate the new features.

## Linked Issue
 #36  [feature] Feature Implementation: Pause/Resume Audio Stream, Save Functionality, and GUI Updates

## Changes and Additions

1. Added pause and resume functionality to audio stream
2. Implemented save function for audio data and frequency plot
3. Introduced audio buffer for saving purposes
4. Enhanced frequency plot with gridlines and legend
5. Adjusted graph canvas size for better visibility
6. Updated GUI layout to accommodate new buttons
7. Added directory selection feature for saving files

## Testing and Validation
The changes were tested manually by running the script and using the new features. The audio stream could be paused and resumed successfully, and the audio data and frequency plot were saved correctly in the selected directory.
Screenshot 2024-05-12 000022
Screenshot 2024-05-12 000041
Screenshot 2024-05-12 000059
Screenshot 2024-05-12 000124

## Additional Context or Information
These enhancements improve the user experience by providing more control over the audio stream and saving options.
## Checklist
Please ensure you've completed the following tasks:

- [x] Code is up to date with the project's latest version
- [x] All tests have been run and passed
- [x] Code has been reviewed for correctness and readability
- [x] Followed the project's coding guidelines

## References
- [Contribution.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Contribution.md)
- [Installation.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Installation.md)
- [References.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/References.md)

### CODE REVIEW

**Comment by Soumya-Kushwaha** [comment]
@RavindranathTagor There's a complete PR template.
Please add description in the same manner.

**Comment by RavindranathTagor** [comment]
## PR Title
Enhancements to Amplitude-Frequency-Visualizer Functionality

## Description
This PR introduces several new features to the Amplitude-Frequency-Visualizer.py script, including the ability to pause and resume the audio stream, save the audio data and frequency plot, and select a directory for saving files. The frequency plot has been enhanced with gridlines and a legend, and the GUI layout has been updated to accommodate the new features.

## Linked Issue
 #36  [feature] Feature Implementation: Pause/Resume Audio Stream, Save Functionality, and GUI Updates

## Changes and Additions

1. Added pause and resume functionality to audio stream
2. Implemented save function for audio data and frequency plot
3. Introduced audio buffer for saving purposes
4. Enhanced frequency plot with gridlines and legend
5. Adjusted graph canvas size for better visibility
6. Updated GUI layout to accommodate new buttons
7. Added directory selection feature for saving files

## Testing and Validation
The changes were tested manually by running the script and using the new features. The audio stream could be paused and resumed successfully, and the audio data and frequency plot were saved correctly in the selected directory.
Screenshot 2024-05-12 000022
Screenshot 2024-05-12 000041
Screenshot 2024-05-12 000059
Screenshot 2024-05-12 000124


## Additional Context or Information
These enhancements improve the user experience by providing more control over the audio stream and saving options.
## Checklist
Please ensure you've completed the following tasks:

- [ ] Code is up to date with the project's latest version
- [ ] All tests have been run and passed
- [ ] Code has been reviewed for correctness and readability
- [ ] Followed the project's coding guidelines

## References
- [Contribution.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Contribution.md)
- [Installation.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Installation.md)
- [References.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/References.md)

**Comment by RavindranathTagor** [comment]
Kindly Review PR.
Could you please add the "GSSoC" and "Level3" labels to this pull request? I believe these labels accurately represent the work done in this PR.
Thank you for your consideration.

**Comment by Soumya-Kushwaha** [comment]
Please add this in the actual PR description (first comment in this thread). Also check in the checklist (if you've done the steps).

Thanks.

**Comment by RavindranathTagor** [comment]
I hope I did it the right way.

**Review by Soumya-Kushwaha — APPROVED** [review]

**Comment by Soumya-Kushwaha** [comment]
Well done.

**Comment by RavindranathTagor** [comment]
Thank you. I am willing to make more contributions to this project.

**Pull request merged**
