### PR TITLE
added the website 

### LINKED ISSUE #124: Feature Request: Designing a Website Explaining the Characteristics of Soundscape Repo[feature]
#### **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't easily find comprehensive information about the features, usage, and characteristics of the Soundscape repository. This makes it difficult for new users to understand what the repo offers and how to use it effectively.

#### **Describe the solution you'd like**
I would like a dedicated website that explains the characteristics of the Soundscape repository. The website should provide an overview of the repository and its key features in a clear and concise manner.

#### **Describe alternatives you've considered**
Alternative solutions could include:
- Improving the README file in the repository with more detailed information and links.
- Creating a series of tutorial videos to explain the repository's features.

#### **Additional context**
Creating a website for the Soundscape repo would help users quickly understand its purpose and how to use it. The website could be hosted on GitHub Pages for easy maintenance and updates.

### PR DESCRIPTION
**Pull request by Harish-2003**
## PR Title
Add dedicated website for Soundscape repository information

## Description
This PR introduces a dedicated website to provide comprehensive information about the Soundscape repository. The website aims to improve user understanding of the repository's features, usage, and characteristics.

## Linked Issue
Resolves #124 website design

## Changes and Additions
- Created a new website hosted on GitHub Pages.
- Added sections detailing repository overview, key features, and usage guidelines.
- Included links to installation instructions, contribution guidelines, and additional references.

## Testing and Validation
The website was tested across multiple browsers (Chrome, Firefox, Safari) and devices (desktop, mobile) to ensure compatibility and responsiveness. Content was reviewed for accuracy and clarity.

## Additional Context or Information
The website is designed to enhance the user experience by offering a centralized resource for understanding Soundscape repository features and usage.

## Checklist
Please ensure you've completed the following tasks:
- [x] Code is up to date with the project's latest version
- [x] All tests have been run and passed
- [x] Code has been reviewed for correctness and readability
- [x] Followed the project's coding guidelines

## References
- [Contribution.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Contribution.md)
- [Installation.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Installation.md)
- [References.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/References.md)

### CODE REVIEW

**Comment by Harish-2003** [comment]
you can see the website design at https://harish-2003.github.io/SoundScape/ after merging you can the website at (https://github.com/Soumya-Kushwaha.github.io/SoundScape)

**Comment by Harish-2003** [comment]
please add some level labels to both the issue and the pr @dinxsh @Soumya-Kushwaha

**Review by dinxsh — CHANGES_REQUESTED** [review]
could you keep the other py files too and not delete them, also add screenshots of the said website you made

**Comment by Harish-2003** [comment]
i think it would best as gh-pages branch is only dedicated for the website it helps us to reduce confusion in the future

**Comment by Harish-2003** [comment]
> could you keep the other py files too and not delete them, also add screenshots of the said website you made

you can see the website at https://harish-2003.github.io/SoundScape/

**Comment by dinxsh** [comment]
great work, keep all the main src py files and we're good to go @Harish-2003

**Comment by Harish-2003** [comment]
Okay will do it by tomorrow and can you please assign some level labels to this pr and the related issue I think level 3 would be great as creating html css and js and merging into other branch is some what more complex

**Comment by Harish-2003** [comment]
have made the changes that you requested @dinxsh i think its good to go and merge it on gh-pages branch now

**Comment by dinxsh** [comment]
apologies, just realized the code was for gh-pages branch, could you revert back to having the website code. sorry for the confusion @Harish-2003

**Comment by Harish-2003** [comment]
how can i revert back? using github website can i do that or do i need to install github desktop for it?

**Comment by Harish-2003** [comment]
done @dinxsh please have a look and let me know is there anything else that i need to do....

**Review by dinxsh — APPROVED** [review]
LGTM, ready for merge. thanks for being patient.

**Comment by Harish-2003** [comment]
> LGTM, ready for merge. thanks for being patient.

can i do revert back using github website? and may i know what is LGTM?

**Comment by Harish-2003** [comment]
### **and i don't know weather you know or not, please don't merge gh-pages with the main branch, maintain gh-pages branch page as seprate as this branch is only for website ** @dinxsh  @Soumya-Kushwaha

**Comment by dinxsh** [comment]
> > LGTM, ready for merge. thanks for being patient.
> 
> can i do revert back using github website? and may i know what is LGTM?

yes, and lgtm is `looks good to me`

**Comment by dinxsh** [comment]
> ### **and i don't know weather you know or not, please don't merge gh-pages with the main branch, maintain gh-pages branch page as seprate as this branch is only for website **
> @dinxsh @Soumya-Kushwaha

i am aware, thanks for clarifying

**Review by dinxsh — APPROVED** [review]
LGTM, ready for merge @Soumya-Kushwaha

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
