### PR TITLE
Enhanced : Add Code of Conduct for Contribution #17

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
**Changes made are**
- Added  Pledge Section
- Added Standards to follow Section
- Added Scope Section
- Added Code for Repository Cloning

**Screenshots are provided below** 
Screenshot 2024-05-10 220631

Screenshot 2024-05-10 220701

Screenshot 2024-05-10 220801

Screenshot 2024-05-10 220825

### CODE REVIEW

**Comment by Soumya-Kushwaha** [comment]
@Santhosh-Siddhardha All of this looks great.

But you've to comment on the issue first, get assigned to the issue, and then proceed to work on the same.
I'll not be able to merge the PR, otherwise.

**Comment by Santhosh-Siddhardha** [comment]
I commented already , but sorry for proceeding before you assigning the issue to me.

**Comment by Soumya-Kushwaha** [comment]
For this time, I'll assign you the issue and merge the PR.
But these are the basic rules you need to take care of, while contributing to any open-source projects.

**Comment by Soumya-Kushwaha** [comment]
@Santhosh-Siddhardha It doesn't work this way.
Also, you've made changes to CONTRIBUTION.md, I wanted a separate file for this.
This is exactly why creating and being assigned on issues is important.

**Comment by Santhosh-Siddhardha** [comment]
Hey @Soumya-Kushwaha ,
Sorry for that and give me one final chance, I can prove myself.

**Comment by Soumya-Kushwaha** [comment]
@Santhosh-Siddhardha Its not about proving anything but only following the general rules.
I've already assigned it to someone who commented before you on the issue.
Please feel free to create new issues and I'll be happy to assign you.

**Pull request closed without merging**
