### PR TITLE
Added model for noise reduction-PCEN

### PR DESCRIPTION
**Pull request by Soubeer**
Added one method of reducing noise from incoming sound.
Uses filtering for low frequencies to capture enough detail and not lose important analytical data.
There is no particular dataset, any sound sample can be used.

### CODE REVIEW

**Comment by Soumya-Kushwaha** [comment]
Please update the fork before raising PR.
Also follow the PR template.

**Comment by Soubeer** [comment]
PR Title
Added model for noise reduction-PCEN

Description
A method of reducing noise from incoming sound has been added
Used filtering for low frequencies to capture enough detail and not lose important analytical data.
There is no particular dataset, any sound sample can be used.

Linked Issue
#[56] [Adding methods to reduce sound noise]

Changes and Additions:
A method of reducing noise from incoming sound has been added
Used filtering for low frequencies to capture enough detail and not lose important analytical data
There is no particular dataset, any sound sample can be used

Testing and Validation
Tested on sound samples to find low frequency zones and correspond the same with sample labels
Successfully reduced sound decibels from incoming noise by checking the sound wave graph

Additional Context or Information
The fork is updated and it only additionally includes the file for the model to work

Checklist
Please ensure you've completed the following tasks:

   Code is up to date with the project's latest version
   All tests have been run and passed
   Code has been reviewed for correctness and readability
   Followed the project's coding guidelines

**Comment by Soubeer** [comment]
@Soumya-Kushwaha I have completed my task long ago, is this still not ok?

**Comment by sanjay-kv** [comment]
Hi @Soumya-Kushwaha please look into it, let me know anything wrong.

**Review by Soumya-Kushwaha — APPROVED** [review]

**Pull request merged**
